export default [
  [4.0, 'celeb', 'Celeb'],
  [2.0, 'width', 'Width'],
  [2.0, 'height', 'Height'],
  [2.0, 'smile', 'Smile'],
  [2.0, 'more_smile', 'Smile B'],
  [2.0, 'mouthopen', 'Mouth Open'],
  [2.0, 'eyesopen', 'Eyes Open'],
  [2.0, 'neutral', 'Neutral'],
  [2.0, 'gender', 'Gender'],
  [2.0, 'more_gender', 'Gender B'],
  [2.0, 'more_age', 'Age'],
  [2.0, 'age_young', 'Age Young'],
  [2.0, 'age_middle', 'Age Middle'],
  [2.0, 'age_old', 'Age Old'],
  [2.0, 'brightness', 'Brightness'],
  [2.0, 'sharpness', 'Sharpness'],
  [2.0, 'skin_asian', 'Skin Asian'],
  [2.0, 'skin_black', 'Skin Black'],
  [2.0, 'glasses', 'Glasses'],
  [2.0, 'more_eyeglasses', 'Glasses B'],
  [2.0, 'hair_blond', 'Hair Blond'],
  [2.0, 'hair_black', 'Hair Black'],
  [2.0, 'hair_brown', 'Hair Brown'],
  [2.0, 'hair_gray', 'Hair Gray'],
  [2.0, 'hair_red', 'Hair Red'],
  [2.0, 'bald', 'Baldness'],
  [2.0, 'facialhair', 'Facialhair'],
  [2.0, 'sideburns', 'Sideburns'],
  [2.0, 'beard', 'Beard'],
  [2.0, 'more_beard', 'Beard B'],
  [2.0, 'moustache', 'Moustache'],
  [2.0, 'more_mustache', 'Moustache B'],
  [2.0, 'lipMakeup', 'Lip Makeup'],
  [2.0, 'eyeMakeup', 'Eye Makeup'],
  [2.0, 'anger', 'Anger'],
  [2.0, 'more_angry', 'Anger B'],
  [2.0, 'fear', 'Fear'],
  [2.0, 'more_confused', 'Confused'],
  [2.0, 'contempt', 'Contempt'],
  [2.0, 'disgust', 'Disgust'],
  [2.0, 'more_disgusted', 'Disgust B'],
  [2.0, 'happiness', 'Happy'],
  [2.0, 'more_happy', 'Happy B'],
  [2.0, 'sadness', 'Sad'],
  [2.0, 'more_sad', 'Sad B'],
  [2.0, 'surprise', 'Surprise'],
  [2.0, 'style', 'Stylize'],
  [2.0, 'headPose_yaw', 'Head Pose Yaw'],
  [2.0, 'headPose_roll', 'Head Pose Roll'],
];

export const sections = [
  {
    title: 'General',
    data: [
      [4.0, 'celeb'],
      [2.0, 'smile'],
      [2.0, 'neutral'],
      [2.0, 'gender'],
    ],
  },
  {
    title: 'Age',
    data: [
      [2.0, 'age_young'],
      [2.0, 'age_middle'],
      [2.0, 'age_old'],
    ],
  },
  {
    title: 'Skin',
    data: [
      [2.0, 'skin_asian'],
      [2.0, 'skin_black'],
    ],
  },
  {
    title: 'Hair',
    data: [
      [2.0, 'hair_blond'],
      [2.0, 'hair_black'],
      [2.0, 'hair_brown'],
      [2.0, 'hair_gray'],
      [2.0, 'hair_red'],
      [2.0, 'bald'],
      [2.0, 'facialhair'],
      [2.0, 'sideburns'],
      [2.0, 'beard'],
      [2.0, 'moustache'],
    ],
  },
  {
    title: 'Accessories',
    data: [
      [2.0, 'glasses'],
      [2.0, 'lipMakeup'],
      [2.0, 'eyeMakeup'],
    ],
  },
  {
    title: 'Mood',
    data: [
      [2.0, 'anger'],
      [2.0, 'fear'],
      [2.0, 'contempt'],
      [2.0, 'disgust'],
      [2.0, 'happiness'],
      [2.0, 'sadness'],
      [2.0, 'surprise'],
    ],
  },
  {
    title: 'Pose',
    data: [
      [2.0, 'headPose_yaw'],
      [2.0, 'headPose_roll'],
    ],
  },
];
