export default [
  [4.0, 'celeb', 'Celeb'],
  [2.0, 'smile', 'Smile'],
  [2.0, 'neutral', 'Neutral'],
  [2.0, 'gender', 'Gender'],
  [2.0, 'age_young', 'Age Young'],
  [2.0, 'age_middle', 'Age Middle'],
  [2.0, 'age_old', 'Age Old'],
  [2.0, 'skin_asian', 'Skin Asian'],
  [2.0, 'skin_black', 'Skin Black'],
  [2.0, 'glasses', 'Glasses'],
  [2.0, 'hair_blond', 'Hair Blond'],
  [2.0, 'hair_black', 'Hair Black'],
  [2.0, 'hair_brown', 'Hair Brown'],
  [2.0, 'hair_gray', 'Hair Gray'],
  [2.0, 'hair_red', 'Hair Red'],
  [2.0, 'bald', 'Bald'],
  [2.0, 'facialhair', 'Facialhair'],
  [2.0, 'sideburns', 'Sideburns'],
  [2.0, 'beard', 'Beard'],
  [2.0, 'moustache', 'Moustache'],
  [2.0, 'lipMakeup', 'Lip Makeup'],
  [2.0, 'eyeMakeup', 'Eye Makeup'],
  [2.0, 'anger', 'Anger'],
  [2.0, 'fear', 'Fear'],
  [2.0, 'contempt', 'Contempt'],
  [2.0, 'disgust', 'Disgust'],
  [2.0, 'happiness', 'Happiness'],
  [2.0, 'sadness', 'Sadness'],
  [2.0, 'surprise', 'Surprise'],
  [2.0, 'headPose_yaw', 'Head Pose Yaw'],
  [2.0, 'headPose_roll', 'Head Pose Roll'],
];
