export default [
  [4.0, 'celeb'],
  [2.0, 'smile'],
  [2.0, 'neutral'],
  [2.0, 'gender'],
  [2.0, 'age_young'],
  [2.0, 'age_middle'],
  [2.0, 'age_old'],
  [2.0, 'skin_asian'],
  [2.0, 'skin_black'],
  [2.0, 'glasses'],
  [2.0, 'hair_blond'],
  [2.0, 'hair_black'],
  [2.0, 'hair_brown'],
  [2.0, 'hair_gray'],
  [2.0, 'hair_red'],
  [2.0, 'bald'],
  [2.0, 'facialhair'],
  [2.0, 'sideburns'],
  [2.0, 'beard'],
  [2.0, 'moustache'],
  [2.0, 'lipMakeup'],
  [2.0, 'eyeMakeup'],
  [2.0, 'anger'],
  [2.0, 'fear'],
  [2.0, 'contempt'],
  [2.0, 'disgust'],
  [2.0, 'happiness'],
  [2.0, 'sadness'],
  [2.0, 'surprise'],
  [2.0, 'headPose_yaw'],
  [2.0, 'headPose_roll'],
];

export const sections = [
  {
    title: 'General',
    data: [
      [4.0, 'celeb'],
      [2.0, 'smile'],
      [2.0, 'neutral'],
      [2.0, 'gender'],
    ],
  },
  {
    title: 'Age',
    data: [
      [2.0, 'age_young'],
      [2.0, 'age_middle'],
      [2.0, 'age_old'],
    ],
  },
  {
    title: 'Skin',
    data: [
      [2.0, 'skin_asian'],
      [2.0, 'skin_black'],
    ],
  },
  {
    title: 'Hair',
    data: [
      [2.0, 'hair_blond'],
      [2.0, 'hair_black'],
      [2.0, 'hair_brown'],
      [2.0, 'hair_gray'],
      [2.0, 'hair_red'],
      [2.0, 'bald'],
      [2.0, 'facialhair'],
      [2.0, 'sideburns'],
      [2.0, 'beard'],
      [2.0, 'moustache'],
    ],
  },
  {
    title: 'Accessories',
    data: [
      [2.0, 'glasses'],
      [2.0, 'lipMakeup'],
      [2.0, 'eyeMakeup'],
    ],
  },
  {
    title: 'Mood',
    data: [
      [2.0, 'anger'],
      [2.0, 'fear'],
      [2.0, 'contempt'],
      [2.0, 'disgust'],
      [2.0, 'happiness'],
      [2.0, 'sadness'],
      [2.0, 'surprise'],
    ],
  },
  {
    title: 'Pose',
    data: [
      [2.0, 'headPose_yaw'],
      [2.0, 'headPose_roll'],
    ],
  },
];
